package pe.edu.idat.web.persistence.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0 2019-06-29T13:57:05.517-05:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", name = "LosGudYobEndpoint")
@XmlSeeAlso({ ObjectFactory.class })
public interface LosGudYobEndpoint {

	@WebMethod
	@RequestWrapper(localName = "eliminarClient", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.EliminarClient")
	@ResponseWrapper(localName = "eliminarClientResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.EliminarClientResponse")
	@WebResult(name = "ClienteUpdateModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.ClienteUpdateModelResponse eliminarClient(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.EliminarModelRequest arg0);

	@WebMethod
	@RequestWrapper(localName = "updateClient", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.UpdateClient")
	@ResponseWrapper(localName = "updateClientResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.UpdateClientResponse")
	@WebResult(name = "ClienteUpdateModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.ClienteUpdateModelResponse updateClient(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.ClienteUpdateModelRequest arg0);

	@WebMethod
	@RequestWrapper(localName = "updateService", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.UpdateService")
	@ResponseWrapper(localName = "updateServiceResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.UpdateServiceResponse")
	@WebResult(name = "ServicioUpdateModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.ServicioUpdateModelResponse updateService(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.ServicioUpdateModelRequest arg0);

	@WebMethod
	@RequestWrapper(localName = "asignarTecnico", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.AsignarTecnico")
	@ResponseWrapper(localName = "asignarTecnicoResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.AsignarTecnicoResponse")
	@WebResult(name = "SolicitudAsignarTecnicoModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.SolicitudAsignarTecnicoModelResponse asignarTecnico(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.SolicitudAsignarTecnicoModelRequest arg0);

	@WebMethod
	@RequestWrapper(localName = "eliminarSolicitud", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.EliminarSolicitud")
	@ResponseWrapper(localName = "eliminarSolicitudResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.EliminarSolicitudResponse")
	@WebResult(name = "ClienteUpdateModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.ClienteUpdateModelResponse eliminarSolicitud(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.EliminarModelRequest arg0);

	@WebMethod
	@RequestWrapper(localName = "insertClient", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.InsertClient")
	@ResponseWrapper(localName = "insertClientResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.InsertClientResponse")
	@WebResult(name = "ClienteRegistroModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.ClienteRegistroModelResponse insertClient(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.ClienteRegistroModelRequest arg0);

	@WebMethod
	@RequestWrapper(localName = "insertService", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.InsertService")
	@ResponseWrapper(localName = "insertServiceResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.InsertServiceResponse")
	@WebResult(name = "ServicioRegistroModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.ServicioRegistroModelResponse insertService(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.ServicioRegistroModelRequest arg0);

	@WebMethod
	@RequestWrapper(localName = "insertSolicitud", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.InsertSolicitud")
	@ResponseWrapper(localName = "insertSolicitudResponse", targetNamespace = "http://endpoint.view.losgudyob.proyecto.pe/", className = "pe.edu.idat.web.persistence.soap.service.InsertSolicitudResponse")
	@WebResult(name = "SolicitudRegistroModelResponse", targetNamespace = "")
	public pe.edu.idat.web.persistence.soap.service.SolicitudRegistroModelResponse insertSolicitud(
			@WebParam(name = "arg0", targetNamespace = "") pe.edu.idat.web.persistence.soap.service.SolicitudRegistroModelRequest arg0);
}
